### ISSUE TITLE
figurepath in look

### ISSUE THREAD

**Issue by cespaillat** [danfeldman90/EDGE#14]
edit look so that it can accept figurepath as an input; currently, it uses the figurepath hardcoded in edge.py, which can lead to confusion when working on many objects and you forget to change figurepath in edge.py and it prevents you from making figures for multiple objects at the same time.  This means xlim and ylim would need to be set as inputs too.

**Comment by danfeldman90** [comment]
look() now has a keyword called savepath, which uses the hardcoded figurepath as the default option. Supplying your own overwrites the default and allows you to no longer have to hard code this path into EDGE.py
