### ISSUE TITLE
edit rchi2 to handle nan / edit look to not plot lines in data gaps

### ISSUE THREAD

**Issue by mrutala** [danfeldman90/EDGE#22]
As it is, if you have a spectra which had parts cut out in spextool, it is stored with nans where the cuts were made, which gives a clean looking plot. However, if rchi2 is used with this pickle, the nans cause it to crash. Without the nans, the spectra will connect points across the cut, giving an odd looking plot.

**Comment by danfeldman90** [comment]
This has been fixed. Chi-squared function now will overlook the NaNs in the spectra.
