### ISSUE TITLE
Merge dered.py into EDGE.py

### ISSUE THREAD

**Issue by danfeldman90** [danfeldman90/EDGE#5]
Need to adapt that code to efficiently work with EDGE structure for merging into the main code.

**Comment by yumiry** [comment]
if your merge both code, you may have to considerate:

1.- To run dered.py the photometry part, the user will need to input the data in flux, can converted that using EDGE.py: convertMag.
2.- With the data in flux and dereddened('obj'_dered_phot.txt), you  only need to create: photwl and photflux, to introduce the data in the pickle file. 

Can skip a few step when makes a pickle file for a target

**Comment by danfeldman90** [comment]
Merged via the new class Red_Obs(), which inherits from TTS_Obs(). This new class contains dered() method for dereddening and outputs a new TTS_Obs() pickle containing the data. You can also use SPPickle() as normal for Red_Obs() to create a pickle with raw data. To read it back in, you must add the red=1 keyword to the loadPickle() function.

Done.
