### ISSUE TITLE
Print out model to a text file

### ISSUE THREAD

**Issue by danfeldman90** [danfeldman90/EDGE#6]
Print out model components and total to a text file with job name nomenclature as the name of the file.

**Comment by cespaillat** [comment]
components: wavelength, total, photosphere, walls (depending on flags), outer disk

label columns in first line

filename - object_001.dat

add flag to multiply walls by a factor given

**Comment by danfeldman90** [comment]
Functionality added to calc_total method in TTS_Model. If you want to save the components into a .dat file, you add the keyword 'save=1' to the function call (without quotes). Similarly, if you want to multiply the inner wall by some value, set the keyword altinh=# and it will do so. Currently does not support outer wall multiplication for PTD.
