### ISSUE TITLE
account for extinction from disk in highly inclined disks

### ISSUE THREAD

**Issue by cespaillat** [danfeldman90/EDGE#7]
For disks that are close to edge-on, the outer disk will extinct the inner disk and the star. To properly account for this, the stellar and wall fluxes must be multiplied by e^(-tau) where tau is the 6th (and last) column in the angle\* file.  The fluxes printed in the angle\* file already take this tau factor into account so this extra e^(-tau) only has to be applied to the star and walls.

**Comment by danfeldman90** [comment]
Should this be a blanket effect applied to the SED, or should it only be when mui is above/below a given threshold?

**Comment by connorrobinson** [comment]
I've updated collate to automatically include the extinction from the outer disk in the flux from the star and the wall. I added the extinction column to the outputted collate file as well.

I've also updated collate to have a 'noextinct' flag incase there is ever a time that you would want to not have this correction applied. This adds a tag to the header: "NOEXT"
